# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - accumax

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install --legacy-peer-deps
          npm run build-prod --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip dist/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'accumax'
          slot-name: 'Production'
          package: ./dist
          publish-profile: <publishData><publishProfile profileName="accumaxx - Web Deploy" publishMethod="MSDeploy" publishUrl="accumaxx.scm.azurewebsites.net:443" msdeploySite="accumaxx" userName="$accumaxx" userPWD="vD09hE9fidXXgGEadr6pTM3GZ8m09L87cF6gXrvQPu9LcA3gorxpKqs5p63M" destinationAppUrl="https://accumaxx.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="accumaxx - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-325.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="accumaxx\$accumaxx" userPWD="vD09hE9fidXXgGEadr6pTM3GZ8m09L87cF6gXrvQPu9LcA3gorxpKqs5p63M" destinationAppUrl="https://accumaxx.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="accumaxx - Zip Deploy" publishMethod="ZipDeploy" publishUrl="accumaxx.scm.azurewebsites.net:443" userName="$accumaxx" userPWD="vD09hE9fidXXgGEadr6pTM3GZ8m09L87cF6gXrvQPu9LcA3gorxpKqs5p63M" destinationAppUrl="https://accumaxx.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
